### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by tfausak** [haskell-actions/hlint-setup#69]
The latest tagged release is from January. There have been a few changes since then, notably #60. Here's the diff: https://github.com/haskell-actions/hlint-setup/compare/0b0024319753ba0c8b2fa21b7018ed252aed8181...87280353856dea2cb5596618b662440634bbcaad

**Comment by mihaimaruseac** [comment]
Sorry for dropping the ball here. I missed the notification. I'll do a release by the end of this week.

As a side note, I'm considering deprecating `hlint-{setup,run}` pair in favor of https://github.com/haskell-actions/hlint-scan but I need to make sure all current users can migrate without being impacted too severely. Can you please take a look and see if you can use `hlint-scan` instead? Thank you!

**Comment by tfausak** [comment]
I hadn't really looked at hlint-scan before. It seems like quite a different thing that hlint-run. 

Poking around a bit, it looks like the version of HLint isn't configurable? It's just whichever version the Docker container happened to pull in, which is currently from Stackage LTS 22.5. I see that the _path_ is configurable, but that would essentially require using hlint-setup.

**Comment by mihaimaruseac** [comment]
That makes sense, thank you for taking a look. In this case, I'll continue maintaining these, at least until `hlint-scan` gets full feature parity

**Comment by mihaimaruseac** [comment]
Created https://github.com/haskell-actions/hlint-setup/releases/tag/v2.4.10 and the equivalent https://github.com/haskell-actions/hlint-run/releases/tag/v2.4.10.

Sorry for the delay.

**Comment by tfausak** [comment]
Thanks!
